export enum CommandName {
  FullBin = "full-bin",
  EmptyBin = "empty-bin",
  RecordPieces = "record-pieces",
  ChangeStatus = "change-status",
  ShopPacket = "shop-packet",
  StartSetup = "start-setup",
  StartRun = "start-run",
  StartIndirect = "start-indirect",
  Stop = "stop",
  StopwoQty = "stop-w/o-qty",
  IssueMaterial = "issue-material",
  Test = "test",
  MyJobs = "my-jobs",
  JobSearch = "job-search",
  ProdReceipt = "prod-receipt",
  TransferMatl = "transfer-matl",
  ScrapMatl = "scrap-matl",
  MiscReceipt = "misc-receipt",
  MiscIssue =  "misc-issue",
  StartDowntime = "start-downtime"
}
